### ISSUE TITLE
Уточнения по поводу "ТЗ"

### ISSUE THREAD

**Issue by phil-dolgolev** [CSC-MobDev-2016/lesson5#1]
А что значит системные иконки? Встроенные в андройд? Так там вроде подходящего ничего нет.
Или я не правильно понял?

**Comment by thevery** [comment]
Речь идёт о том, чтобы для .pdf, например, показывать иконку текущего pdf-ридера.

**Comment by phil-dolgolev** [comment]
Можете тогда подсказать?

Я прилично времени убил перелопачивая гугл, как же вытащить именно одно дефолтное приложение, чтобы проставить его иконку на файл, но у меня не вышло. Последнее что пробовал:

```
                final Intent intent = new Intent(Intent.ACTION_VIEW);
                String mimeType = MimeTypeMap.getSingleton().getMimeTypeFromExtension(item.getName().substring(item.getName().lastIndexOf(".") + 1));
                intent.setData(Uri.fromFile(item.getFile()));
                intent.setType(mimeType);
                final List<ResolveInfo> matches = context.getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
```

Но здесь в matches получается их несколько, всегда, даже когда выставлено дефолтное.
В общем, у меня уже никаких идей нет, и нагуглить не получается :(

**Comment by thevery** [comment]
Скорее всего нужно не использовать mimetype. Возьмите пока первый из списка, я как посмотрю напишу свой вариант.

**Comment by thevery** [comment]
и да, нужно использовать метод `setDataAndType`

**Comment by thevery** [comment]
upd: для получения однозначного ответа нужно использовать `getPackageManager().resolveActivity(intent, 0)`, плюс см. http://stackoverflow.com/a/23820594/195671

**Comment by thevery** [comment]
```
MimeTypeMap myMime = MimeTypeMap.getSingleton();
String mimeType = myMime.getMimeTypeFromExtension(fileExt(file.getName()));
intent.setDataAndType(Uri.parse(file.getName()), mimeType);
```
