### ISSUE TITLE
listFiles возвращает null, permission.READ_EXTERNAL_STORAGE не помогает

### ISSUE THREAD

**Issue by malinovsky239** [CSC-MobDev-2016/lesson5#8]
Никак не могу преодолеть следующую проблему: 
`(new File(Environment.DIRECTORY_DOWNLOADS)).listFiles()` возвращает `null`.

Везде пишут про проблемы с permission'ами. Но `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />` в манифесте есть, `Manifest.permission.READ_EXTERNAL_STORAGE` в `MainActivity.onCreate` я запрашиваю, а `listFiles` возвращает `null` по-прежнему.

Подскажите, пожалуйста, что ещё может быть не так.

**Comment by thevery** [comment]
Надо юзать `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).listFiles();`

**Comment by malinovsky239** [comment]
@thevery Спасибо!
